CREATE DATABASE `ONEMORE_DB` /*!40100 DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI */ /*!80016 DEFAULT ENCRYPTION='N' */;

------Tables---

CREATE TABLE `TEST_CASE` (
  `ID` VARCHAR(10) NOT NULL,
  `TESTCASE_NAME` VARCHAR(45) DEFAULT NULL,
  `DESCRIPTION` VARCHAR(45) DEFAULT NULL,
  `WORKSPACE` VARCHAR(10) NOT NULL,
  `USER` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_FK_IDX` (`USER`),
  KEY `WORKSPCAE_FK_IDX` (`WORKSPACE`),
  CONSTRAINT `USER_FK_TS` FOREIGN KEY (`USER`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `WORKSPCAE_FK` FOREIGN KEY (`WORKSPACE`) REFERENCES `WORKSPACE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `USERS` (
  `ID` VARCHAR(10) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(150) NOT NULL,
  `CREATED` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME_UNIQUE` (`USERNAME`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `WORKSPACE` (
  `ID` VARCHAR(10) NOT NULL,
  `WORKSPACE_NAME` VARCHAR(150) NOT NULL,
  `DESCRIPTION` VARCHAR(500) DEFAULT NULL,
  `USER` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID_IDX` (`USER`),
  CONSTRAINT `USER_FK` FOREIGN KEY (`USER`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;




------ SEQUENCE -------

CREATE TABLE USER_SEQ
(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);


DELIMITER $$
CREATE TRIGGER USER_TABLE_ID_INSERT
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  INSERT INTO USER_SEQ VALUES (NULL);
  SET NEW.ID = CONCAT('ONE_U', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;


CREATE TABLE WORKSPACE_SEQ
(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);


DELIMITER $$
CREATE TRIGGER WORKSPACE_TABLE_ID_INSERT
BEFORE INSERT ON WORKSPACE
FOR EACH ROW
BEGIN
  INSERT INTO WORKSPACE_SEQ VALUES (NULL);
  SET NEW.ID = CONCAT('ONE_WS', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;



CREATE TABLE TESTCASE_SEQ
(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);


DELIMITER $$
CREATE TRIGGER TESTCASE_TABLE_ID_INSERT
BEFORE INSERT ON TEST_CASE
FOR EACH ROW
BEGIN
  INSERT INTO TESTCASE_SEQ VALUES (NULL);
  SET NEW.ID = CONCAT('ONE_TC', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;